version: '3.8'

services:
 drupal:
  image: drupal:latest
  ports:
   - 8081:80
  volumes:
   - /var/www/html/modules
   - /var/www/html/profiles
   - /var/www/html/themes
   - /var/www/html/sites
  restart: always

 mysql:
  image: mysql:latest
  command: --default-authentication-plugin=mysql_native_password
  ports: 
   - 3306
  environment:
   MYSQL_DATABASE: drupal
   MYSQL_ROOT_PASSWORD: admin

